<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['smtp_accounts_system_not_initialized_warning'] = 'чтобы активировать все опции на сервере SMTP, система учетных записей должна быть инициализирована';
$lang['smtp_app_description'] = 'Сервер SMTP предоставляет возможность для входящей и исходящей почты, а также передачу почты и функции аутентификации SMTP.';
$lang['smtp_app_name'] = 'SMTP Сервер';
$lang['smtp_block_plaintext'] = 'Блокировать незашифрованные пароли';
$lang['smtp_configure_accounts'] = 'Настройка Аккаунта';
$lang['smtp_destination_domains'] = 'Целевой домен';
$lang['smtp_mail_disclaimer_invalid'] = 'Mail disclaimer is invalid.';
$lang['smtp_mail_forwarding'] = 'Переадресация почты';
$lang['smtp_mail_settings_in_mail_app_message'] = 'The hostname and domain settings can be configured in the Mail Settings app.';
$lang['smtp_maximum_message_size'] = 'Максимальный размер сообщения';
$lang['smtp_port_invalid'] = 'Порт является недействительным.';
$lang['smtp_recipient_mapping_invalid'] = 'Recipient mapping is invalid.';
$lang['smtp_relay_host'] = 'Релейный узел';
$lang['smtp_relay_host_invalid'] = 'Релейный узел - инвалид.';
$lang['smtp_server_invalid'] = 'SMTP Сервер является недействительным.';
$lang['smtp_smtp_authentication'] = 'Аутентификация SMTP';
$lang['smtp_smtp_server'] = 'SMTP Сервер';
$lang['smtp_target_server'] = 'Целевой сервер';
$lang['smtp_trusted_network_invalid'] = 'Надежная сеть - инвалид.';
$lang['smtp_trusted_networks'] = 'Доверенные сети';
$lang['smtp_user_policies'] = 'Политика пользователей';
