<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['smtp_accounts_system_not_initialized_warning'] = 'Aby skorzystać ze wszystkich funkcji serwera SMTP, konta systemowe muszą być zainicjowane';
$lang['smtp_app_description'] = 'Serwer SMTP dostarcza serwer pocztowy dla wiadomości przychodzących i wychodzących jak również funkcje przekierowywania wiadomości oraz uwierzytelnienia SMTP.';
$lang['smtp_app_name'] = 'Serwer SMTP';
$lang['smtp_block_plaintext'] = 'Zablokuj hasła z czystego tekstu';
$lang['smtp_configure_accounts'] = 'Skonfiguruj konta';
$lang['smtp_destination_domains'] = 'Domeny docelowe';
$lang['smtp_mail_disclaimer_invalid'] = 'Stopa pocztowa jest nieprawidłowa.';
$lang['smtp_mail_forwarding'] = 'Przekierowywanie poczty';
$lang['smtp_mail_settings_in_mail_app_message'] = 'Ustawienia nazwy hosta oraz domeny mogą zostać skonfigurowane w aplikacji Ustawienia poczty.';
$lang['smtp_maximum_message_size'] = 'Maksymalny rozmiar wiadomości';
$lang['smtp_port_invalid'] = 'Port jest nieprawidłowy.';
$lang['smtp_recipient_mapping_invalid'] = 'Mapowanie odbiorcy jest nieprawidłowe.';
$lang['smtp_relay_host'] = 'Host przekazywania';
$lang['smtp_relay_host_invalid'] = 'Host przekazywania jest nieprawidłowy.';
$lang['smtp_server_invalid'] = 'Serwer SMTP jest nieprawidłowy.';
$lang['smtp_smtp_authentication'] = 'Uwierzytelnianie SMTP';
$lang['smtp_smtp_server'] = 'Serwer SMTP';
$lang['smtp_target_server'] = 'Serwer docelowy';
$lang['smtp_trusted_network_invalid'] = 'Zaufana sieć jest nieprawidłowa.';
$lang['smtp_trusted_networks'] = 'Zaufane sieci';
$lang['smtp_user_policies'] = 'Reguły użytkowników';
